name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit requests
    
    - name: Install Neovim
      run: |
        curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        chmod u+x nvim.appimage
        sudo mv nvim.appimage /usr/local/bin/nvim
    
    - name: Test CLI functionality
      run: |
        chmod +x nvim-secscan
        echo "flask==0.12.2" > requirements.txt
        echo "import os; os.system('ls')" > test.py
        ./nvim-secscan --help
        ./nvim-secscan test.py
    
    - name: Run security scan on self
      run: |
        python scripts/secscan-cli.py scripts/secscan-cli.py || true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit flake8
    
    - name: Run bandit security scan
      run: bandit -r scripts/ -f json || true
    
    - name: Run flake8 linting
      run: flake8 scripts/ --max-line-length=100 || true